### ISSUE TITLE
[Bug]: Spatie website for documentation is not up to date

### ISSUE THREAD

**Issue by mhfereydouni** [spatie/laravel-notification-log#16]
### What happened?

The docs are ok in the GitHub repository but the website is not updated with the last version of the documentation.

### How to reproduce the bug

for publishing config the specified tag in the website is wrong:
[https://spatie.be/docs/laravel-notification-log/v1/installation-setup](https://spatie.be/docs/laravel-notification-log/v1/installation-setup)
but it is ok on GitHub:
[https://github.com/spatie/laravel-notification-log/blob/main/docs/installation-setup.md](https://github.com/spatie/laravel-notification-log/blob/main/docs/installation-setup.md)

### Package Version

1.03

### PHP Version

8.2

### Laravel Version

10.8

**Comment by freekmurze** [comment]
This has been fixed.

**Comment by mhfereydouni** [comment]
but the website is still showing the wrong tag for config publishment
https://spatie.be/docs/laravel-notification-log/v1/installation-setup#:~:text=php%20artisan%20vendor%3Apublish%20%2D%2Dtag%3D%22laravel%2Dnotification%2Dlog%2Dconfig%22

**Comment by freekmurze** [comment]
You're a fast one, the import process was still busy. All good now!
